# Generated by Django 3.0.8 on 2020-07-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '家长表',
                'verbose_name_plural': '家长表',
            },
        ),
    ]
