# Generated by Django 3.0.8 on 2020-07-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='userId',
        ),
    ]
